version: '3.1'
services:
  app:
    image: aronpc/php:8.2-nginx
    working_dir: /app
    environment:
      XDEBUG_MODE: coverage
    ports:
      - '${APP_PORT:-8080}:8080'
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - mail

  mysql:
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - 'mysql:/var/lib/mysql'

  mail:
    image: 'axllent/mailpit:latest'
    ports:
      - '${MAIL_PORT:-1025}:1025'
      - '${MAIL_DASHBOARD_PORT:-8025}:8025'

volumes:
  mysql: